/**
 * 1. THE BASE INTERFACE
 * This is our primary data structure representing a user in the system.
 */
interface User {
  id: number;
  username: string;
  email: string;
  age: number;
  isAdmin: boolean;
  createdAt: Date;
}

/**
 * 2. Partial<T>
 * Use case: Profile Updates.
 * When a user edits their profile, they usually don't change every single field.
 * Partial makes all properties in the User interface OPTIONAL.
 */
type UserUpdateInput = Partial<User>;

const updateMyProfile = (id: number, changes: UserUpdateInput) => {
  // TypeScript is happy even if we only provide one or two fields
  console.log(`Updating user ${id} with:`, changes);
};

// Example: We are only updating the age. Other fields are skipped safely.
updateMyProfile(101, { age: 26 }); 


/**
 * 3. Pick<T, K>
 * Use case: UI Displays or Summaries.
 * Often, we have a large object but the UI only needs a small part of it.
 * Pick allows us to "select" specific keys to create a new, leaner type.
 */
type UserLeaderboardInfo = Pick<User, "username" | "age">;

const topUsers: UserLeaderboardInfo[] = [
  { username: "Sabbir", age: 22 },
  { username: "Nabila", age: 24 }
  // We cannot add 'email' or 'id' here; TypeScript will block it.
];


/**
 * 4. Omit<T, K>
 * Use case: Form Submissions / Creating Data.
 * When registering a new user, fields like 'id' and 'createdAt' are usually 
 * generated by the database, so we don't want to include them in the initial form.
 * Omit "drops" specific keys and keeps everything else.
 */
type NewUserRegistration = Omit<User, "id" | "createdAt">;

const registerUser = (userData: NewUserRegistration) => {
  // This ensures we don't accidentally try to manually set an ID or Timestamp
  console.log("Registering new user:", userData.username);
};

registerUser({
  username: "Arif_Dev",
  email: "arif@example.com",
  age: 30,
  isAdmin: false
});

/**
 * QUICK SUMMARY FOR YOUR REFERENCE:
 * * - Partial: Makes everything optional (Good for Updates/Edits).
 * - Pick: Takes only the keys you list (Good for specific UI components).
 * - Omit: Removes the keys you list and keeps the rest (Good for filtering sensitive/auto-gen data).
 */